package companySearcher.cxf.cis.bir.publ._2014._07;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-14T12:50:52.842+02:00
 * Generated source version: 3.1.12
 */
@WebService(targetNamespace = "http://CIS/BIR/PUBL/2014/07", name = "IUslugaBIRzewnPubl")
@XmlSeeAlso({companySearcher.cxf.com.microsoft.schemas._2003._10.serialization.ObjectFactory.class, companySearcher.cxf.cis.bir.publ._2014._07.datacontract.ObjectFactory.class, ObjectFactory.class, companySearcher.cxf.cis.bir._2014._07.ObjectFactory.class})
public interface IUslugaBIRzewnPubl {

    @WebMethod(operationName = "SetValue", action = "http://CIS/BIR/2014/07/IUslugaBIR/SetValue")
    @Action(input = "http://CIS/BIR/2014/07/IUslugaBIR/SetValue", output = "http://CIS/BIR/2014/07/IUslugaBIR/SetValueResponse")
    @RequestWrapper(localName = "SetValue", targetNamespace = "http://CIS/BIR/2014/07", className = "SetValue")
    @ResponseWrapper(localName = "SetValueResponse", targetNamespace = "http://CIS/BIR/2014/07", className = "SetValueResponse")
    @WebResult(name = "SetValueResult", targetNamespace = "http://CIS/BIR/2014/07")
    java.lang.String setValue(
            @WebParam(name = "pNazwaParametru", targetNamespace = "http://CIS/BIR/2014/07")
                    java.lang.String pNazwaParametru,
            @WebParam(name = "pWartoscParametru", targetNamespace = "http://CIS/BIR/2014/07")
                    java.lang.String pWartoscParametru
    );

    @WebMethod(operationName = "DaneSzukaj", action = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukaj")
    @Action(input = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukaj", output = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneSzukajResponse")
    @RequestWrapper(localName = "DaneSzukaj", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "DaneSzukaj")
    @ResponseWrapper(localName = "DaneSzukajResponse", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "DaneSzukajResponse")
    @WebResult(name = "DaneSzukajResult", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
    java.lang.String daneSzukaj(
            @WebParam(name = "pParametryWyszukiwania", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
                    companySearcher.cxf.cis.bir.publ._2014._07.datacontract.ParametryWyszukiwania pParametryWyszukiwania
    );

    @WebMethod(operationName = "SprawdzCaptcha", action = "http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptcha")
    @Action(input = "http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptcha", output = "http://CIS/BIR/2014/07/IUslugaBIR/SprawdzCaptchaResponse")
    @RequestWrapper(localName = "SprawdzCaptcha", targetNamespace = "http://CIS/BIR/2014/07", className = "SprawdzCaptcha")
    @ResponseWrapper(localName = "SprawdzCaptchaResponse", targetNamespace = "http://CIS/BIR/2014/07", className = "SprawdzCaptchaResponse")
    @WebResult(name = "SprawdzCaptchaResult", targetNamespace = "http://CIS/BIR/2014/07")
    java.lang.Boolean sprawdzCaptcha(
            @WebParam(name = "pCaptcha", targetNamespace = "http://CIS/BIR/2014/07")
                    java.lang.String pCaptcha
    );

    @WebMethod(operationName = "GetValue", action = "http://CIS/BIR/2014/07/IUslugaBIR/GetValue")
    @Action(input = "http://CIS/BIR/2014/07/IUslugaBIR/GetValue", output = "http://CIS/BIR/2014/07/IUslugaBIR/GetValueResponse")
    @RequestWrapper(localName = "GetValue", targetNamespace = "http://CIS/BIR/2014/07", className = "GetValue")
    @ResponseWrapper(localName = "GetValueResponse", targetNamespace = "http://CIS/BIR/2014/07", className = "GetValueResponse")
    @WebResult(name = "GetValueResult", targetNamespace = "http://CIS/BIR/2014/07")
    java.lang.String getValue(
            @WebParam(name = "pNazwaParametru", targetNamespace = "http://CIS/BIR/2014/07")
                    java.lang.String pNazwaParametru
    );

    @WebMethod(operationName = "Zaloguj", action = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj")
    @Action(input = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Zaloguj", output = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/ZalogujResponse")
    @RequestWrapper(localName = "Zaloguj", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "Zaloguj")
    @ResponseWrapper(localName = "ZalogujResponse", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "ZalogujResponse")
    @WebResult(name = "ZalogujResult", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
    java.lang.String zaloguj(
            @WebParam(name = "pKluczUzytkownika", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
                    java.lang.String pKluczUzytkownika
    );

    @WebMethod(operationName = "Wyloguj", action = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj")
    @Action(input = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/Wyloguj", output = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/WylogujResponse")
    @RequestWrapper(localName = "Wyloguj", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "Wyloguj")
    @ResponseWrapper(localName = "WylogujResponse", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "WylogujResponse")
    @WebResult(name = "WylogujResult", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
    java.lang.Boolean wyloguj(
            @WebParam(name = "pIdentyfikatorSesji", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
                    java.lang.String pIdentyfikatorSesji
    );

    @WebMethod(operationName = "DaneKomunikat", action = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikat")
    @Action(input = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikat", output = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DaneKomunikatResponse")
    @RequestWrapper(localName = "DaneKomunikat", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "DaneKomunikat")
    @ResponseWrapper(localName = "DaneKomunikatResponse", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "DaneKomunikatResponse")
    @WebResult(name = "DaneKomunikatResult", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
    java.lang.String daneKomunikat();

    @WebMethod(operationName = "PobierzCaptcha", action = "http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptcha")
    @Action(input = "http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptcha", output = "http://CIS/BIR/2014/07/IUslugaBIR/PobierzCaptchaResponse")
    @RequestWrapper(localName = "PobierzCaptcha", targetNamespace = "http://CIS/BIR/2014/07", className = "PobierzCaptcha")
    @ResponseWrapper(localName = "PobierzCaptchaResponse", targetNamespace = "http://CIS/BIR/2014/07", className = "PobierzCaptchaResponse")
    @WebResult(name = "PobierzCaptchaResult", targetNamespace = "http://CIS/BIR/2014/07")
    java.lang.String pobierzCaptcha();

    @WebMethod(operationName = "DanePobierzPelnyRaport", action = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaport")
    @Action(input = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaport", output = "http://CIS/BIR/PUBL/2014/07/IUslugaBIRzewnPubl/DanePobierzPelnyRaportResponse")
    @RequestWrapper(localName = "DanePobierzPelnyRaport", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "DanePobierzPelnyRaport")
    @ResponseWrapper(localName = "DanePobierzPelnyRaportResponse", targetNamespace = "http://CIS/BIR/PUBL/2014/07", className = "DanePobierzPelnyRaportResponse")
    @WebResult(name = "DanePobierzPelnyRaportResult", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
    java.lang.String danePobierzPelnyRaport(
            @WebParam(name = "pRegon", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
                    java.lang.String pRegon,
            @WebParam(name = "pNazwaRaportu", targetNamespace = "http://CIS/BIR/PUBL/2014/07")
                    java.lang.String pNazwaRaportu
    );
}
